name: ESM
channels: 
  - defaults
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit=11.3
  - pip
  - dask
  - distributed
  - rasterio
  - pip:
    - DeepForest
    - pytest
    - comet_ml
